### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by ghost** [muoncore/photon#18] opened 2017-06-15 07:34 UTC
Muon Version: 7.2.9 (io.muoncore/muon-clojure)
Language: clojure

Services in Use: Not sure

I am running the latest photon (https://github.com/muoncore/photon/commit/5a93239a1cbac27e7ac12e4e03c563c072848aa3) and have received the following stack trace. I'm starting photon with this command line:

`java -jar photon-*-standalone.jar -muon.url amqp://guest:guest@rabbitmq -ui.port 3500 -db.backend mongo`

`StreamServerChannel$1@3d21092a]
08:48:43.377 INFO  [photon.muon] (channel-5) PhotonMS: {:stream-name saga-lifecycle, :stream-type hot-cold, :from 1497449887212208}
08:48:43.377 INFO  [photon.streams] (channel-5) {:stream-name "saga-lifecycle", :stream-type "hot-cold", :from "1497449887212208"}
08:48:43.377 INFO  [photon.streams] (channel-5) stream type: hot-cold
08:48:43.377 INFO  [photon.streams] (channel-5) Initialising hot-cold stream with params {:stream-name "saga-lifecycle", :stream-type "hot-cold", :from "1497449887212208"}
08:48:43.377 INFO  [photon.streams] (channel-5) Getting stream-name and data
08:48:43.377 INFO  [photon.streams] (channel-5) Finished getting stream-name and data
08:48:43.377 INFO  [muon-clojure.rx] (channel-5) Assigned channel: 1933587362
08:48:43.377 INFO  [photon.streams] (async-dispatch-6) data-from saga-lifecycle 1497449887212208
08:48:43.377 INFO  [io.muoncore.codec.DelegatingCodecs] (channel-5) Encoding {}/class java.util.HashMap with content type [application/json]
08:48:43.378 INFO  [photon.streams] (async-dispatch-6) :::::::::::::::::::: Stream depleted, switching to hot stream
08:48:43.381 INFO  [io.muoncore.codec.DelegatingCodecs] (channel-5) Decoding class io.muoncore.protocol.reactivestream.messages.RequestMessage with content type application/json [123, 34, 114, 101, 113, 117, 101, 115, 116, 34, 58, 57, 50, 50, 51, 51, 55, 50, 48, 51, 54, 56, 53, 52, 55, 55, 53, 56, 48, 55, 125]
08:48:43.382 INFO  [muon-clojure.rx] (channel-5) ::::: SUBSCRIPTION #object[io.muoncore.protocol.reactivestream.server.ReactiveStreamServerChannel$1 0x3d21092a io.muoncore.protocol.reactivestream.server.ReactiveStreamServerChannel$1@3d21092a] :: request 9223372036854775807
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
	at java.util.HashMap.putMapEntries(HashMap.java:511)
	at java.util.HashMap.<init>(HashMap.java:489)
	at io.muoncore.transport.ServiceCache.expire(ServiceCache.java:21)
	at io.muoncore.transport.ServiceCache.getServices(ServiceCache.java:34)
	at io.muoncore.extension.amqp.discovery.AmqpDiscovery.getKnownServices(AmqpDiscovery.java:108)
	at io.muoncore.discovery.MultiDiscovery.lambda$getKnownServices$0(MultiDiscovery.java:24)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.muoncore.discovery.MultiDiscovery.getKnownServices(MultiDiscovery.java:24)
	at io.muoncore.Discovery.findService(Discovery.java:24)
	at io.muoncore.Discovery.getCodecsForService(Discovery.java:28)
	at io.muoncore.extension.amqp.AmqpMessageTransformers.outboundToQueue(AmqpMessageTransformers.java:13)
	at io.muoncore.extension.amqp.DefaultAmqpChannel.lambda$send$2(DefaultAmqpChannel.java:169)
	at io.muoncore.transport.client.RingBufferLocalDispatcher.route(RingBufferLocalDispatcher.java:404)
	at io.muoncore.transport.client.RingBufferLocalDispatcher$SingleThreadTask.run(RingBufferLocalDispatcher.java:297)
	at io.muoncore.transport.client.RingBufferLocalDispatcher$3.onEvent(RingBufferLocalDispatcher.java:171)
	at io.muoncore.transport.client.RingBufferLocalDispatcher$3.onEvent(RingBufferLocalDispatcher.java:168)
	at reactor.jarjar.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by daviddawson** [comment] 2017-06-15 08:15
Is this stack trace within photon or a client?

**Comment by tranchis** [comment] 2017-06-15 08:31
@johangwbasson There should be a dump of env at the beginning of the photon logs with a dump of env. If you manage to find it, can you post it here? Thanks!

**Comment by ghost** [comment] 2017-06-15 12:12
Unfortunately it is logging to the console and the terminal cannot scroll as far back

**Comment by ghost** [comment] 2017-06-15 12:12
The stack trace is within photon

**Comment by daviddawson** [comment] 2017-06-16 10:35
This is caused by https://github.com/muoncore/muon-java/issues/55

This was fixed in muon-java 7.2.10.  Upgrading the muon-java version to that will fix this.

**Closed as completed** 2017-06-17 01:46 UTC
